<?xml version="1.0" encoding="utf-8"?><Database Name="DoAn" Class="DbWebGiayDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MSI\SQLEXPRESS;Initial Catalog=DoAn;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DoAnConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID_Cat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="ID_Cat" OtherKey="ID_Cat" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="ID_news" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NSX" Member="NSXes">
    <Type Name="NSX">
      <Column Name="ID_NSX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNsx" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NSX_Product" Member="Products" ThisKey="ID_NSX" OtherKey="ID_NSX" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="ID_Order" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_KH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Create_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Order_Order_detail" Member="Order_details" ThisKey="ID_Order" OtherKey="ID_Product" Type="Order_detail" />
      <Association Name="User_Order" Member="User" ThisKey="ID_KH" OtherKey="ID_KH" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_detail" Member="Order_details">
    <Type Name="Order_detail">
      <Column Name="ID_Product" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_KH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Order_Order_detail" Member="Order" ThisKey="ID_Product" OtherKey="ID_Order" Type="Order" IsForeignKey="true" />
      <Association Name="Product_Order_detail" Member="Product" ThisKey="ID_Product" OtherKey="ID_Product" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID_Product" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Cat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_NSX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Img" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Update_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Product_Order_detail" Member="Order_details" ThisKey="ID_Product" OtherKey="ID_Product" Type="Order_detail" />
      <Association Name="Category_Product" Member="Category" ThisKey="ID_Cat" OtherKey="ID_Cat" Type="Category" IsForeignKey="true" />
      <Association Name="NSX_Product" Member="NSX" ThisKey="ID_NSX" OtherKey="ID_NSX" Type="NSX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID_KH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Order" Member="Orders" ThisKey="ID_KH" OtherKey="ID_KH" Type="Order" />
    </Type>
  </Table>
</Database>